# 系统参数配置
server:
  port: 8080

spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:oracle:thin:@192.168.88.65:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: lvuser
    password: lvuser
    tomcat:
      initial-size: 30
      max-active: 150
      max-wait: 100000
      max-idle: 150
      min-idle: 10